server.port=8081
spring.datasource.url=jdbc:h2:mem:roomdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.listener.auto-startup=true
spring.kafka.producer.retries=0
spring.kafka.producer.properties.max.block.ms=1000
